#pragma once



namespace Hawk{
	class CharacterStream;
	
	class Tokenizer{
		public:
			Tokenizer(CharacterStream& char_stream) : stream(char_stream) {};
			~Tokenizer() = default;


			void start();

			struct Token{
				enum class Type;
				Type type;
				uint line = 0;
				uint collumn = 0;
				std::string value = "";

			};

			inline bool success() const { return !this->has_errored; };

		public:
			std::vector<Token> tokens;

		private:
			void make_token(Token::Type type);
			void process_char();

			bool process_comments();
			bool process_id();
			bool process_number();
			bool process_operators();
			bool process_punctuation();

			void move_while(std::function<bool()> condition);
			void move_while_newline();

			bool is_whitespace();
			bool is_letter(char _char);
			bool is_letter();
			bool is_number(char _char);
			bool is_number();

			void error();

		private:
			CharacterStream& stream;
			
			char character;
			std::string token_val = "";

			bool has_errored = false;
	};




	enum class Tokenizer::Token::Type{
		none,
		generated, // used if generated by the compiler

		id,
		literal_number,
		literal_bool,

		// keywords
		keyword_func,
		keyword_return,
		keyword_if,
		keyword_else,

		// built in types
		type_void,
		type_int,
		type_bool,

		// operators
		assign,
		type_def,
		const_type_def,

		op_plus,
		op_minus,
		op_mult,
		op_div,

		// puncutation
		semicolon,
		comma,
		open_paren,
		close_paren,
		open_brace,
		close_brace,
	};

	using TokenType = Tokenizer::Token::Type;


}

